export const CHANGE_DAY = 'CHANGE_DAY';
export const CHANGE_YEAR_AND_MONTH = 'CHANGE_YEAR_AND_MONTH';
export const CHANGE_SESSION = 'CHANGE_SESSION';
export const POST_REMINDER = 'POST_REMINDER';
export const GET_SINGLE_REMINDER = 'GET_SINGLE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
