export const CHANGE_DAY = 'CHANGE_DAY';
export const CHANGE_YEAR_AND_MONTH = 'CHANGE_YEAR_AND_MONTH';
export const POST_REMINDER = 'POST_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';

export const CHANGE_SESSION_YEAR = 'CHANGE_SESSION_YEAR';
export const CHANGE_SESSION_MONTH = 'CHANGE_SESSION_MONTH';
export const CHANGE_SESSION_DAY = 'CHANGE_SESSION_DAY';
export const CHANGE_SESSION_HOUR = 'CHANGE_SESSION_HOUR';
export const CHANGE_SESSION_MINUTE = 'CHANGE_SESSION_MINUTE';
export const CHANGE_SESSION_REMINDER = 'CHANGE_SESSION_REMINDER';
export const CLEAN_SESSION = 'CLEAN_SESSION';
